package visual;

import main.Main;
import modelo.*;
import servico.*;
import utilitario.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;

public class TelaSecretaria extends javax.swing.JFrame {
    private Integer idPacienteEdicao = null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaSecretaria.class.getName());
       
    /**
     * Creates new form TelaSecretaria
     */
    public TelaSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUf = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rbPlanoDeSaude = new javax.swing.JRadioButton();
        rbParticular = new javax.swing.JRadioButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPacientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cbPaciente = new javax.swing.JComboBox<>();
        cbMedico = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtDataHora = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        rbNormal = new javax.swing.JRadioButton();
        rbRetorno = new javax.swing.JRadioButton();
        btnAgendar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        rbEmail = new javax.swing.JRadioButton();
        rbSmsTelefone = new javax.swing.JRadioButton();
        btnGerar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome Completo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 9, -1, -1));

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 118, 300, -1));

        jLabel2.setText("CPF:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 37, -1));

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 34, 300, -1));

        jLabel3.setText("Data Nascimento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 65, -1, -1));

        try {
            txtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 62, 300, -1));

        jLabel4.setText("Rua:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 90, 37, -1));

        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });
        jPanel1.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 90, 300, -1));

        jLabel5.setText("Número:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 118, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 6, 300, -1));

        jLabel6.setText("Complemento:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 149, -1, -1));

        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });
        jPanel1.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 146, 300, -1));

        jLabel7.setText("Bairro:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, 37, -1));

        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 174, 300, -1));

        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 202, -1, -1));

        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 202, 300, -1));

        jLabel9.setText("UF:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 230, 37, -1));

        try {
            txtUf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 230, 300, -1));

        jLabel10.setText("Telefone:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 258, -1, -1));

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 258, 300, -1));

        jLabel11.setText("E-mail:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 43, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 286, 300, -1));

        jLabel12.setText("Convênio:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        buttonGroup1.add(rbPlanoDeSaude);
        rbPlanoDeSaude.setText("Plano de Saúde");
        rbPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlanoDeSaudeActionPerformed(evt);
            }
        });
        jPanel1.add(rbPlanoDeSaude, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 314, -1, -1));

        buttonGroup1.add(rbParticular);
        rbParticular.setText("Particular");
        rbParticular.setToolTipText("");
        rbParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParticularActionPerformed(evt);
            }
        });
        jPanel1.add(rbParticular, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 314, 98, -1));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 341, 75, -1));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 341, 75, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 341, 75, -1));

        tabelaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPacientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 376, 790, 170));

        jTabbedPane1.addTab("Pacientes", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPacienteActionPerformed(evt);
            }
        });
        jPanel2.add(cbPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        cbMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        jLabel13.setText("Data/Hora:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        try {
            txtDataHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 300, -1));

        jLabel14.setText("Tipo:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        buttonGroup2.add(rbNormal);
        rbNormal.setText("Normal");
        jPanel2.add(rbNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        buttonGroup2.add(rbRetorno);
        rbRetorno.setText("Retorno");
        rbRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRetornoActionPerformed(evt);
            }
        });
        jPanel2.add(rbRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 76, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Data/Hora", "Paciente", "Médico", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 104, 780, -1));

        jLabel15.setText("Paciente:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel16.setText("Médico:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        jTabbedPane1.addTab("Consultas", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Filtrar Por:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        rbEmail.setText("Email");
        rbEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmailActionPerformed(evt);
            }
        });
        jPanel3.add(rbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 6, -1, -1));

        rbSmsTelefone.setText("SMS/Telefone");
        rbSmsTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSmsTelefoneActionPerformed(evt);
            }
        });
        jPanel3.add(rbSmsTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 6, 114, -1));

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, 75, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 780, 460));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 790, 10));

        jTabbedPane1.addTab("Relatórios", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void rbParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbParticularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbParticularActionPerformed

    private void rbPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlanoDeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPlanoDeSaudeActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        try {
            if (cbPaciente.getSelectedIndex() <= 0 || cbMedico.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this, "Selecione Paciente e Médico.");
                return;
            }

            Paciente p = (Paciente) cbPaciente.getSelectedItem();
            Medico m = (Medico) cbMedico.getSelectedItem();
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            LocalDateTime dataHora = LocalDateTime.parse(txtDataHora.getText(), dtf);
            TipoConsulta tipo = rbNormal.isSelected() ? TipoConsulta.NORMAL : TipoConsulta.RETORNO;

            Main.secretariaServico.cadastrarConsulta(dataHora, m, p, tipo);
            JOptionPane.showMessageDialog(this, "Agendado!");
            atualizarTabelaConsultas();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void rbRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRetornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRetornoActionPerformed

    private void rbEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEmailActionPerformed

    private void rbSmsTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSmsTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSmsTelefoneActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        String filtro = rbEmail.isSelected() ? "EMAIL" : "TELEFONE";
        LocalDateTime amanha = LocalDate.now().plusDays(1).atStartOfDay();
        
        List<Consulta> lista = Main.secretariaServico.gerarRelatorioConsultas(amanha, filtro);
        
        StringBuilder sb = new StringBuilder();
        sb.append("--- RELATÓRIO DE AMANHÃ (" + filtro + ") ---\n");
        
        for (Consulta c : lista) {
            sb.append("Paciente: ").append(c.getPaciente().getNome());
            sb.append(" | Hora: ").append(c.getDataHora().toLocalTime());
            
            if (filtro.equals("EMAIL")) 
                sb.append(" | Email: ").append(c.getPaciente().getContato().getEmail());
            else 
                sb.append(" | SMS: ").append(c.getPaciente().getContato().getTelefone());
                
            sb.append("\n");
        }
        
        if (lista.isEmpty()) sb.append("Nenhuma consulta encontrada.");
        
        jTextArea1.setText(sb.toString());
        
        if (filtro.equals("EMAIL")) Main.gerenciadorDeMensagensServico.enviarEmails(lista);
        else Main.gerenciadorDeMensagensServico.enviarMensagensSMS(lista);
    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            String nome = txtNome.getText();
            String cpf = txtCpf.getText();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dataNasc = LocalDate.parse(txtDataNasc.getText(), dtf);
            
            Endereco endereco = new Endereco(
                txtRua.getText(), txtNumero.getText(), txtComplemento.getText(),
                txtBairro.getText(), txtCidade.getText(), txtUf.getText()
            );
            Contato contato = new Contato(txtTelefone.getText(), txtEmail.getText());
            TipoConvenio convenio = rbParticular.isSelected() ? TipoConvenio.PARTICULAR : TipoConvenio.PLANO_SAUDE;

            if (idPacienteEdicao == null) {
                Main.pacienteServico.cadastrarPaciente(nome, cpf, dataNasc, endereco, contato, convenio);
                JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
            } else {
                Main.secretariaServico.atualizarPaciente(idPacienteEdicao, nome, endereco, contato, convenio);
                JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
            }

            limparCamposPacientes();
            atualizarTabelaPacientes();
            preencherComboBoxes();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (idPacienteEdicao == null) {
            JOptionPane.showMessageDialog(this, "Selecione um paciente na tabela.");
            return;
        }
        
        if (JOptionPane.showConfirmDialog(this, "Excluir paciente?", "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            Main.secretariaServico.removerPaciente(idPacienteEdicao);
            limparCamposPacientes();
            atualizarTabelaPacientes();
            preencherComboBoxes();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tabelaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPacientesMouseClicked
        int linha = tabelaPacientes.getSelectedRow();
        if (linha >= 0) {
            // Pega o ID da coluna 0
            idPacienteEdicao = (Integer) tabelaPacientes.getValueAt(linha, 0);
            
            Paciente p = Main.pacienteServico.buscarPacientePorId(idPacienteEdicao);
            if (p != null) {
                txtNome.setText(p.getNome());
                txtCpf.setText(p.getCpf());
                txtDataNasc.setText(p.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                txtTelefone.setText(p.getContato().getTelefone());
                txtEmail.setText(p.getContato().getEmail());
                
                txtRua.setText(p.getEndereco().getRua());
                txtNumero.setText(p.getEndereco().getNumero());
                txtComplemento.setText(p.getEndereco().getComplemento());
                txtBairro.setText(p.getEndereco().getBairro());
                txtCidade.setText(p.getEndereco().getCidade());
                txtUf.setText(p.getEndereco().getUf());
                
                if (p.getTipoConvenio() == TipoConvenio.PARTICULAR) rbParticular.setSelected(true);
                else rbPlanoDeSaude.setSelected(true);
            }
        }
    }//GEN-LAST:event_tabelaPacientesMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int linha = jTable1.getSelectedRow();
        if (linha >= 0) {
            int id = (Integer) jTable1.getValueAt(linha, 0);
            Main.secretariaServico.removerConsulta(id);
            atualizarTabelaConsultas();
            JOptionPane.showMessageDialog(this, "Cancelada.");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma consulta.");
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaSecretaria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<Object> cbMedico;
    private javax.swing.JComboBox<Object> cbPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rbEmail;
    private javax.swing.JRadioButton rbNormal;
    private javax.swing.JRadioButton rbParticular;
    private javax.swing.JRadioButton rbPlanoDeSaude;
    private javax.swing.JRadioButton rbRetorno;
    private javax.swing.JRadioButton rbSmsTelefone;
    private javax.swing.JTable tabelaPacientes;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataHora;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JFormattedTextField txtUf;
    // End of variables declaration//GEN-END:variables
    // --- MÉTODOS AUXILIARES ---

    private void limparCamposPacientes() {
        txtNome.setText("");
        txtCpf.setText("");
        txtDataNasc.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtUf.setText("");
        txtTelefone.setText("");
        txtEmail.setText(""); // Note o 'x' extra conforme seu código
        rbParticular.setSelected(true);
        
        idPacienteEdicao = null; // Reseta a edição
    }

    private void atualizarTabelaPacientes() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaPacientes.getModel();
        modelo.setNumRows(0);
        
        for (Paciente p : Main.pacienteServico.getListaPacientes()) {
            modelo.addRow(new Object[]{
                p.getId(), p.getNome(), p.getCpf(), p.getContato().getTelefone()
            });
        }
    }

    private void atualizarTabelaConsultas() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel(); // Sua tabela chama jTable1
        modelo.setNumRows(0);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        
        for (Consulta c : Main.consultaServico.getListaConsultas()) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getDataHora().format(dtf),
                c.getPaciente().getNome(),
                c.getMedico().getNome(),
                c.getTipo()
            });
        }
    }

    private void preencherComboBoxes() {
        // Pacientes
        DefaultComboBoxModel modelP = (DefaultComboBoxModel) cbPaciente.getModel();
        modelP.removeAllElements();
        modelP.addElement("Selecione...");
        for (Paciente p : Main.pacienteServico.getListaPacientes()) {
            modelP.addElement(p);
        }

        // Médicos
        DefaultComboBoxModel modelM = (DefaultComboBoxModel) cbMedico.getModel();
        modelM.removeAllElements();
        modelM.addElement("Selecione...");
        for (Medico m : Main.medicosDaClinica) {
            modelM.addElement(m);
        }
    }
}
